woowa-techcamp-2021/baemin-18

- .gitignore
- package-lock.json
- package.json
- src/index.js
- src/routers/join-router.js
- src/routers/login-router.js
- src/views/join.pug
- src/views/login.pug
- src/views/main.pug
> [#4] 라우터 구성

- src/public/reset.css
- src/public/style.css
resolve #8 
- reset.css
- box-sizing, 기본 margin, padding 제거 등..
- input-text
- 로그인, 비밀번호, 가입, input 입력에 사용
- arrow-more
- 더보기 화살표 (메인, 회원가입)
- label-check
- input 유효성 확인
- btn-large
- 로그인, 회원가입, 다음으로 버튼 스타일
- btn-clear
- input 입력 값 삭제
Co-authored-by: Jiho-Moon <jiho9505@users.noreply.github.com>
> [#8] 공통 UI 구현

- src/public/style.css
- src/views/blocks/header.pug
- src/views/main.pug
- style.css
- body 스타일 작성
- header 스타일 작성
- header.pug
> [#8] 공통 UI 구현 - 2

- package-lock.json
- package.json
- src/routers/join-router.js
기본적인 틀 구현 완료!
에러 처리 및 리팩토링은 추후 협의 예정입니다.
> [#6] 회원가입 구현

- src/js/join-phone.js
- src/public/join-phone.css
- src/public/style.css
- src/views/join-phone.pug
- src/views/mixins/input-block.pug
resolve #12 
- join-phone
- 입력한 번호는 로컬스토리지에 저장 처리
- style.css
- 공통 css 추가 작성 (hidden, visible)
- input-block
- alertText 하드코딩 제거
> [#12] 회원가입 2/3 페이지 UI 및 기능 구현

- src/routers/login-router.js
1. user 중복 체크
2. hash된 pwd와 입력된 pwd 비교
3. jwt.sign을 통한 토큰 발행
4. 토큰을 쿠키에 담는다.
초고 (미완성 & 리뷰용)
추후 리팩토링 예정
> [#7] login router 구현

- src/js/join-agree.js
- src/js/join-phone.js
- src/public/join-agree.css
- src/public/join-phone.css
- src/public/style.css
- src/views/join-agree.pug
- src/views/join-phone.pug
- src/views/mixins/input-block.pug
resolve #11 
- join-agree.js
- 체크박스 관련 이벤트 구현
- 유효성 검사 구현
- join-agree.css
- next-btn 클래스 추가
- 버튼 active 속성 추가 및 기존 btn 클래스 패딩 제거
> [#11] 회원가입 1/3 페이지 UI 및 기능 구현

- src/js/join-agree.js
- src/js/join-info.js
- src/js/join-phone.js
- src/public/join-agree.css
- src/public/join-phone.css
- src/public/style.css
- src/views/join-agree.pug
- src/views/join-info.pug
- src/views/join-phone.pug
- src/views/mixins/input-block.pug
커밋 메세지에서 보신 바와 같이 현재 비밀번호 검증에 미비사항이 있으며,  
현재 작업 중 입니다!  
코드 검토를 위해 PR 먼저 작성합니다!
> [#13] 회원가입 3/3 페이지 UI 및 기능 구현

- src/apis/pwd.js
- src/middleware/auth.js
- src/routers/join-router.js
- src/routers/login-router.js
resolve #14
1. bcrypt 를 api 디렉토리로 이동
2. DB까지 safe Pwd 저장 완료
> [#14] 안전한 패스워드 저장

- src/js/join-agree.js
- src/js/join-info.js
- src/js/join-phone.js
- src/public/join-agree.css
- src/public/join-phone.css
- src/public/login.css
- src/public/style.css
- src/views/join-agree.pug
- src/views/join-info.pug
- src/views/join-phone.pug
- src/views/login.pug
- src/views/mixins/input-block.pug
resolve #9 
기획서에서 소셜 로그인 관련 버튼을 제외하고 구현하였습니다.
> [#9] 로그인 페이지 UI 구현

- src/js/join-agree.js
- src/js/join-info.js
- src/js/join-phone.js
- src/js/login.js
- src/public/join-agree.css
- src/public/join-phone.css
- src/public/login.css
- src/public/style.css
- src/views/join-agree.pug
- src/views/join-info.pug
- src/views/join-phone.pug
- src/views/login.pug
- src/views/mixins/input-block.pug
resolve #10 
이메일 및 비밀번호 입력 후 로그인 데이터 전달까지 확인하였습니다.  
유효성 검사는 커밋 메세지에 남긴 바와 같이 길이만 검사하고 있습니다.
> [#10] 로그인 페이지 기능 구현

- package-lock.json
- package.json
- src/apis/pwd.js
- src/apis/token.js
- src/middleware/auth.js
- src/routers/join-router.js
- src/routers/login-router.js
resolve #10
1. jwt 사용해 쿠키에 담아넣었다.
2. jwt 관련 메소드 분리
3. bcrypt로 암호화 pwd 해독 가능
4. cookie-parser 추가
> [#10] 로그인 기능 구현 끝

- package-lock.json
- package.json
- src/apis/pwd.js
- src/apis/token.js
- src/middleware/auth.js
- src/routers/join-router.js
- src/routers/login-router.js
1. user 접속 했을시 닉네임 표시
2. jwt로 접속 여부 확인
> [#29] 권한인증 구현

- src/js/join-agree.js
- src/js/join-info.js
- src/js/join-phone.js
- src/js/login.js
- src/js/main.js
- src/public/join-agree.css
- src/public/join-phone.css
- src/public/login.css
- src/public/main.css
- src/public/style.css
- src/views/join-agree.pug
- src/views/join-info.pug
- src/views/join-phone.pug
- src/views/login.pug
- src/views/main.pug
- src/views/mixins/input-block.pug
resolve #15 
- 로그인 페이지로의 이동에 대해서 간단하게 작업했습니다.
- 기본 스타일 수정 및 500px이하의 환경에서의 크기 조정 처리했습니다.
> [#15] 메인 페이지 기능 구현

- README.md
- src/js/join-agree.js
- src/js/join-info.js
- src/js/join-phone.js
- src/public/join-phone.css
- src/routers/login-router.js
> [#42] 마무리 작업 및 배포

- src/routers/main-router.js
resolve #43
- 유저의 DB 정보에서 token 값 초기화
> [#43] 로그아웃 구현

- src/js/main.js
- src/public/main.css
- src/views/main.pug
> [#43] 로그아웃 프론트 UI 및 기능 구현

- src/js/join-info.js
- src/js/main.js
- src/public/join-agree.css
- src/public/style.css
- src/routers/main-router.js
- src/views/main.pug
> [#42] 마무리 작업 및 배포 - 2

- src/public/login.css
- src/views/login.pug
> [#42] 로그인 UI 최종 수정

- src/js/join-agree.js
- src/js/join-info.js
- src/js/join-phone.js
- src/js/main.js
- src/public/join-agree.css
- src/public/join-info.css
- src/public/join-phone.css
- src/public/style.css
- src/views/join-agree.pug
- src/views/join-info.pug
- src/views/join-phone.pug
- UI 수정
-  페이지마다 헤더와 바디의 위치가 일치하지 않는 현상을 발견하여 수정 처리
- 로딩 UI 구현
- 대기시간이 발생하는 인증번호 요청, 중복확인에 로딩 추가
- 중복검사 구현
- fetch 요청으로 처리
> [#42] 마무리 작업 및 배포 - 3, UI 수정 및 로딩, 중복검사 구현

- package-lock.json
- package.json
- src/js/join-phone.ts
- 헤로쿠 배포 오류 package.json 수정
- getVerifyCode 함수 미호출 수정
> [#54] 버그 픽스

- package-lock.json
- package.json
- src/apis/token.ts
- src/middleware/auth.ts
- src/routers/login-router.ts
- 4.3.5에서 버전이 업그레이드 되면서 타입 검사가 더 엄격해졌습니다 :(
- 명확한 원인을 찾아봐야겠어요....
> [#54] :gear: 타입스크립트 4.4.2에서 에러 발생 수정
